name: Generate Pacman Animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write 
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Generate Light Mode Pacman Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          SVG_OUTPUT_PATH: assets/generated/pacman-contribution-graph.svg

   
      - name: Generate Dark Mode Pacman Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          SVG_OUTPUT_PATH: assets/generated/pacman-contribution-graph-dark.svg
          PACMAN_BACKGROUND_COLOR: "0d1117"    
          PACMAN_WALL_COLOR: "21262d"       
          PACMAN_COLOR: "58a6ff"          
          PACMAN_POINT_COLOR: "c9d1d9"      
          PACMAN_GHOST_COLOR: "8b949e"     
          PACMAN_LOADING_COLOR: "c9d1d9" 


      - name: Commit and Push Generated Pacman Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add assets/generated/pacman-contribution-graph.svg assets/generated/pacman-contribution-graph-dark.svg

          if ! git diff --staged --quiet; then
            git commit -m "chore: update pacman contribution animation 팩맨"
            git push
          else
            echo "No changes to commit for Pacman animation."
          fi
